<?php

namespace Database\Seeders;

use App\Models\Department;
use App\Models\Municipality;
use Illuminate\Database\Seeder;

class MunicipalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            '01' => [
                ['name' => 'La Ceiba', 'code' => '0101'],
                ['name' => 'El Porvenir', 'code' => '0102'],
                ['name' => 'Esparta', 'code' => '0103'],
                ['name' => 'Jutiapa', 'code' => '0104'],
                ['name' => 'La Masica', 'code' => '0105'],
                ['name' => 'San Francisco', 'code' => '0106'],
                ['name' => 'Tela', 'code' => '0107'],
                ['name' => 'Arizona', 'code' => '0108'],
            ],
            '02' => [
                ['name' => 'Trujillo', 'code' => '0201'],
                ['name' => 'Balfate', 'code' => '0202'],
                ['name' => 'Iriona', 'code' => '0203'],
                ['name' => 'Limón', 'code' => '0204'],
                ['name' => 'Sabá', 'code' => '0205'],
                ['name' => 'Santa Fe', 'code' => '0206'],
                ['name' => 'Santa Rosa de Aguán', 'code' => '0207'],
                ['name' => 'Sonaguera', 'code' => '0208'],
                ['name' => 'Tocoa', 'code' => '0209'],
                ['name' => 'Bonito Oriental', 'code' => '0210'],
            ],
            '03' => [
                ['name' => 'Comayagua', 'code' => '0301'],
                ['name' => 'Ajuterique', 'code' => '0302'],
                ['name' => 'El Rosario', 'code' => '0303'],
                ['name' => 'Esquías', 'code' => '0304'],
                ['name' => 'Humuya', 'code' => '0305'],
                ['name' => 'La Libertad', 'code' => '0306'],
                ['name' => 'Lamaní', 'code' => '0307'],
                ['name' => 'La Trinidad', 'code' => '0308'],
                ['name' => 'Lejamaní', 'code' => '0309'],
                ['name' => 'Meámbar', 'code' => '0310'],
                ['name' => 'Minas de Oro', 'code' => '0311'],
                ['name' => 'Ojo de Agua', 'code' => '0312'],
                ['name' => 'San Jerónimo', 'code' => '0313'],
                ['name' => 'San José de Comayagua', 'code' => '0314'],
                ['name' => 'San José del Potrero', 'code' => '0315'],
                ['name' => 'San Luis', 'code' => '0316'],
                ['name' => 'San Sebastián', 'code' => '0317'],
                ['name' => 'Siguatepeque', 'code' => '0318'],
                ['name' => 'Villa de San Antonio', 'code' => '0319'],
                ['name' => 'Lajas', 'code' => '0320'],
                ['name' => 'Taulabé', 'code' => '0321'],
            ],
            '04' => [
                ['name' => 'Santa Rosa de Copán', 'code' => '0401'],
                ['name' => 'Cabañas', 'code' => '0402'],
                ['name' => 'Concepción', 'code' => '0403'],
                ['name' => 'Copán Ruinas', 'code' => '0404'],
                ['name' => 'Corquín', 'code' => '0405'],
                ['name' => 'Cucuyagua', 'code' => '0406'],
                ['name' => 'Dolores', 'code' => '0407'],
                ['name' => 'Dulce Nombre', 'code' => '0408'],
                ['name' => 'El Paraíso', 'code' => '0409'],
                ['name' => 'Florida', 'code' => '0410'],
                ['name' => 'La Jigua', 'code' => '0411'],
                ['name' => 'La Unión', 'code' => '0412'],
                ['name' => 'Nueva Arcadia', 'code' => '0413'],
                ['name' => 'San Agustín', 'code' => '0414'],
                ['name' => 'San Antonio', 'code' => '0415'],
                ['name' => 'San Jerónimo', 'code' => '0416'],
                ['name' => 'San José', 'code' => '0417'],
                ['name' => 'San Juan de Opoa', 'code' => '0418'],
                ['name' => 'San Nicolás', 'code' => '0419'],
                ['name' => 'San Pedro', 'code' => '0420'],
                ['name' => 'Santa Rita', 'code' => '0421'],
                ['name' => 'Trinidad de Copán', 'code' => '0422'],
                ['name' => 'Veracruz', 'code' => '0423'],
            ],
            '05' => [
                ['name' => 'San Pedro Sula', 'code' => '0501'],
                ['name' => 'Choloma', 'code' => '0502'],
                ['name' => 'Omoa', 'code' => '0503'],
                ['name' => 'Pimienta', 'code' => '0504'],
                ['name' => 'Potrerillos', 'code' => '0505'],
                ['name' => 'Puerto Cortés', 'code' => '0506'],
                ['name' => 'San Antonio de Cortés', 'code' => '0507'],
                ['name' => 'San Francisco de Yojoa', 'code' => '0508'],
                ['name' => 'San Manuel', 'code' => '0509'],
                ['name' => 'Santa Cruz de Yojoa', 'code' => '0510'],
                ['name' => 'Villanueva', 'code' => '0511'],
                ['name' => 'La Lima', 'code' => '0512'],
            ],
            '06' => [
                ['name' => 'Choluteca', 'code' => '0601'],
                ['name' => 'Apacilagua', 'code' => '0602'],
                ['name' => 'Concepción de María', 'code' => '0603'],
                ['name' => 'Duyure', 'code' => '0604'],
                ['name' => 'El Corpus', 'code' => '0605'],
                ['name' => 'El Triunfo', 'code' => '0606'],
                ['name' => 'Marcovia', 'code' => '0607'],
                ['name' => 'Morolica', 'code' => '0608'],
                ['name' => 'Namasigüe', 'code' => '0609'],
                ['name' => 'Orocuina', 'code' => '0610'],
                ['name' => 'Pespire', 'code' => '0611'],
                ['name' => 'San Antonio de Flores', 'code' => '0612'],
                ['name' => 'San Isidro', 'code' => '0613'],
                ['name' => 'San José', 'code' => '0614'],
                ['name' => 'San Marcos de Colón', 'code' => '0615'],
                ['name' => 'Santa Ana de Yusguare', 'code' => '0616'],
            ],
            '07' => [
                ['name' => 'Yuscarán', 'code' => '0701'],
                ['name' => 'Alauca', 'code' => '0702'],
                ['name' => 'Danlí', 'code' => '0703'],
                ['name' => 'El Paraíso', 'code' => '0704'],
                ['name' => 'Güinope', 'code' => '0705'],
                ['name' => 'Jacaleapa', 'code' => '0706'],
                ['name' => 'Liure', 'code' => '0707'],
                ['name' => 'Morocelí', 'code' => '0708'],
                ['name' => 'Oropolí', 'code' => '0709'],
                ['name' => 'Potrerillos', 'code' => '0710'],
                ['name' => 'San Antonio de Flores', 'code' => '0711'],
                ['name' => 'San Lucas', 'code' => '0712'],
                ['name' => 'San Matías', 'code' => '0713'],
                ['name' => 'Soledad', 'code' => '0714'],
                ['name' => 'Teupasenti', 'code' => '0715'],
                ['name' => 'Texiguat', 'code' => '0716'],
                ['name' => 'Vado Ancho', 'code' => '0717'],
                ['name' => 'Yauyupe', 'code' => '0718'],
                ['name' => 'Trojes', 'code' => '0719'],
            ],
            '08' => [
                ['name' => 'Tegucigalpa D.C.', 'code' => '0801'],
                ['name' => 'Alubarén', 'code' => '0802'],
                ['name' => 'Cedros', 'code' => '0803'],
                ['name' => 'Curarén', 'code' => '0804'],
                ['name' => 'El Porvenir', 'code' => '0805'],
                ['name' => 'Guaimaca', 'code' => '0806'],
                ['name' => 'La Libertad', 'code' => '0807'],
                ['name' => 'La Venta', 'code' => '0808'],
                ['name' => 'Lepaterique', 'code' => '0809'],
                ['name' => 'Maraita', 'code' => '0810'],
                ['name' => 'Marale', 'code' => '0811'],
                ['name' => 'Nueva Armenia', 'code' => '0812'],
                ['name' => 'Ojojona', 'code' => '0813'],
                ['name' => 'Orica', 'code' => '0814'],
                ['name' => 'Reitoca', 'code' => '0815'],
                ['name' => 'Sabanagrande', 'code' => '0816'],
                ['name' => 'San Antonio de Oriente', 'code' => '0817'],
                ['name' => 'San Buenaventura', 'code' => '0818'],
                ['name' => 'San Ignacio', 'code' => '0819'],
                ['name' => 'San Juan de Flores', 'code' => '0820'],
                ['name' => 'San Miguelito', 'code' => '0821'],
                ['name' => 'Santa Ana', 'code' => '0822'],
                ['name' => 'Santa Lucía', 'code' => '0823'],
                ['name' => 'Talanga', 'code' => '0824'],
                ['name' => 'Tatumbla', 'code' => '0825'],
                ['name' => 'Valle de Ángeles', 'code' => '0826'],
                ['name' => 'Villa de San Francisco', 'code' => '0827'],
                ['name' => 'Vallecillo', 'code' => '0828'],
            ],
            '09' => [
                ['name' => 'Puerto Lempira', 'code' => '0901'],
                ['name' => 'Brus Laguna', 'code' => '0902'],
                ['name' => 'Ahuas', 'code' => '0903'],
                ['name' => 'Juan Francisco Bulnes', 'code' => '0904'],
                ['name' => 'Villeda Morales', 'code' => '0905'],
                ['name' => 'Wampusirpi', 'code' => '0906'],
            ],
            '10' => [
                ['name' => 'La Esperanza', 'code' => '1001'],
                ['name' => 'Camasca', 'code' => '1002'],
                ['name' => 'Colomoncagua', 'code' => '1003'],
                ['name' => 'Concepción', 'code' => '1004'],
                ['name' => 'Dolores', 'code' => '1005'],
                ['name' => 'Intibucá', 'code' => '1006'],
                ['name' => 'Jesús de Otoro', 'code' => '1007'],
                ['name' => 'Magdalena', 'code' => '1008'],
                ['name' => 'Masaguara', 'code' => '1009'],
                ['name' => 'San Antonio', 'code' => '1010'],
                ['name' => 'San Isidro', 'code' => '1011'],
                ['name' => 'San Juan de Flores', 'code' => '1012'],
                ['name' => 'San Marcos de La Sierra', 'code' => '1013'],
                ['name' => 'San Miguel Guancapla', 'code' => '1014'],
                ['name' => 'Santa Lucía', 'code' => '1015'],
                ['name' => 'Yamaranguila', 'code' => '1016'],
                ['name' => 'San Francisco Opalaca', 'code' => '1017'],
            ],
            '11' => [
                ['name' => 'Roatán', 'code' => '1101'],
                ['name' => 'Guanaja', 'code' => '1102'],
                ['name' => 'José Santos Guardiola', 'code' => '1103'],
                ['name' => 'Utila', 'code' => '1104'],
            ],
            '12' => [
                ['name' => 'La Paz', 'code' => '1201'],
                ['name' => 'Aguanqueterique', 'code' => '1202'],
                ['name' => 'Cabañas', 'code' => '1203'],
                ['name' => 'Cane', 'code' => '1204'],
                ['name' => 'Chinacla', 'code' => '1205'],
                ['name' => 'Guajiquiro', 'code' => '1206'],
                ['name' => 'Lauterique', 'code' => '1207'],
                ['name' => 'Marcala', 'code' => '1208'],
                ['name' => 'Mercedes de Oriente', 'code' => '1209'],
                ['name' => 'Opatoro', 'code' => '1210'],
                ['name' => 'San Antonio del Norte', 'code' => '1211'],
                ['name' => 'San José', 'code' => '1212'],
                ['name' => 'San Juan', 'code' => '1213'],
                ['name' => 'San Pedro de Tutule', 'code' => '1214'],
                ['name' => 'Santa Ana', 'code' => '1215'],
                ['name' => 'Santa Elena', 'code' => '1216'],
                ['name' => 'Santa María', 'code' => '1217'],
                ['name' => 'Santiago Puringla', 'code' => '1218'],
                ['name' => 'Yarula', 'code' => '1219'],
            ],
            '13' => [
                ['name' => 'Gracias', 'code' => '1301'],
                ['name' => 'Belén', 'code' => '1302'],
                ['name' => 'Candelaria', 'code' => '1303'],
                ['name' => 'Cololaca', 'code' => '1304'],
                ['name' => 'Erandique', 'code' => '1305'],
                ['name' => 'Gualcinse', 'code' => '1306'],
                ['name' => 'Guarita', 'code' => '1307'],
                ['name' => 'La Campa', 'code' => '1308'],
                ['name' => 'La Iguala', 'code' => '1309'],
                ['name' => 'Las Flores', 'code' => '1310'],
                ['name' => 'La Unión', 'code' => '1311'],
                ['name' => 'La Virtud', 'code' => '1312'],
                ['name' => 'Lepaera', 'code' => '1313'],
                ['name' => 'Mapulaca', 'code' => '1314'],
                ['name' => 'Piraera', 'code' => '1315'],
                ['name' => 'San Andrés', 'code' => '1316'],
                ['name' => 'San Francisco', 'code' => '1317'],
                ['name' => 'San Juan Guarita', 'code' => '1318'],
                ['name' => 'San Manuel Colohete', 'code' => '1319'],
                ['name' => 'San Rafael', 'code' => '1320'],
                ['name' => 'San Sebastián', 'code' => '1321'],
                ['name' => 'Santa Cruz', 'code' => '1322'],
                ['name' => 'Talgua', 'code' => '1323'],
                ['name' => 'Tambla', 'code' => '1324'],
                ['name' => 'Tomalá', 'code' => '1325'],
                ['name' => 'Valladolid', 'code' => '1326'],
                ['name' => 'Virginia', 'code' => '1327'],
                ['name' => 'San Marcos de Caiquín', 'code' => '1328'],
            ],
            '14' => [
                ['name' => 'Nueva Ocotepeque', 'code' => '1401'],
                ['name' => 'Belén Gualcho', 'code' => '1402'],
                ['name' => 'Concepción', 'code' => '1403'],
                ['name' => 'Dolores Merendón', 'code' => '1404'],
                ['name' => 'Fraternidad', 'code' => '1405'],
                ['name' => 'La Encarnación', 'code' => '1406'],
                ['name' => 'La Labor', 'code' => '1407'],
                ['name' => 'Lucerna', 'code' => '1408'],
                ['name' => 'Mercedes', 'code' => '1409'],
                ['name' => 'San Fernando', 'code' => '1410'],
                ['name' => 'San Francisco del Valle', 'code' => '1411'],
                ['name' => 'San Jorge', 'code' => '1412'],
                ['name' => 'San Marcos', 'code' => '1413'],
                ['name' => 'Santa Fé', 'code' => '1414'],
                ['name' => 'Sensenti', 'code' => '1415'],
                ['name' => 'Sinuapa', 'code' => '1416'],
            ],
            '15' => [
                ['name' => 'Juticalpa', 'code' => '1501'],
                ['name' => 'Campamento', 'code' => '1502'],
                ['name' => 'Catacamas', 'code' => '1503'],
                ['name' => 'Concordia', 'code' => '1504'],
                ['name' => 'Dulce Nombre de Culmí', 'code' => '1505'],
                ['name' => 'El Rosario', 'code' => '1506'],
                ['name' => 'Esquipulas del Norte', 'code' => '1507'],
                ['name' => 'Gualaco', 'code' => '1508'],
                ['name' => 'Guarizama', 'code' => '1509'],
                ['name' => 'Guata', 'code' => '1510'],
                ['name' => 'Guayape', 'code' => '1511'],
                ['name' => 'Jano', 'code' => '1512'],
                ['name' => 'La Unión', 'code' => '1513'],
                ['name' => 'Mangulile', 'code' => '1514'],
                ['name' => 'Manto', 'code' => '1515'],
                ['name' => 'Salamá', 'code' => '1516'],
                ['name' => 'San Esteban', 'code' => '1517'],
                ['name' => 'San Francisco de Becerra', 'code' => '1518'],
                ['name' => 'San Francisco de La Paz', 'code' => '1519'],
                ['name' => 'Santa María del Real', 'code' => '1520'],
                ['name' => 'Silca', 'code' => '1521'],
                ['name' => 'Yocón', 'code' => '1522'],
                ['name' => 'Patuca', 'code' => '1523'],
            ],
            '16' => [
                ['name' => 'Santa Bárbara', 'code' => '1601'],
                ['name' => 'Arada', 'code' => '1602'],
                ['name' => 'Atima', 'code' => '1603'],
                ['name' => 'Azacualpa', 'code' => '1604'],
                ['name' => 'Ceguaca', 'code' => '1605'],
                ['name' => 'Colinas', 'code' => '1606'],
                ['name' => 'Concepción del Norte', 'code' => '1607'],
                ['name' => 'Concepción del Sur', 'code' => '1608'],
                ['name' => 'Chinda', 'code' => '1609'],
                ['name' => 'El Níspero', 'code' => '1610'],
                ['name' => 'Gualala', 'code' => '1611'],
                ['name' => 'Ilama', 'code' => '1612'],
                ['name' => 'Macuelizo', 'code' => '1613'],
                ['name' => 'Naranjito', 'code' => '1614'],
                ['name' => 'Nueva Celilac', 'code' => '1615'],
                ['name' => 'Petoa', 'code' => '1616'],
                ['name' => 'Protección', 'code' => '1617'],
                ['name' => 'Quimistán', 'code' => '1618'],
                ['name' => 'San Francisco de Ojuera', 'code' => '1619'],
                ['name' => 'San Luis', 'code' => '1620'],
                ['name' => 'San Marcos', 'code' => '1621'],
                ['name' => 'San Nicolás', 'code' => '1622'],
                ['name' => 'San Pedro Zacapa', 'code' => '1623'],
                ['name' => 'Santa Rita', 'code' => '1624'],
                ['name' => 'San Vicente Centenario', 'code' => '1625'],
                ['name' => 'Trinidad', 'code' => '1626'],
                ['name' => 'Las Vegas', 'code' => '1627'],
                ['name' => 'Nueva Frontera', 'code' => '1628'],
            ],
            '17' => [
                ['name' => 'Nacaome', 'code' => '1701'],
                ['name' => 'Alianza', 'code' => '1702'],
                ['name' => 'Amapala', 'code' => '1703'],
                ['name' => 'Aramecina', 'code' => '1704'],
                ['name' => 'Caridad', 'code' => '1705'],
                ['name' => 'Goascorán', 'code' => '1706'],
                ['name' => 'Langue', 'code' => '1707'],
                ['name' => 'San Francisco de Coray', 'code' => '1708'],
                ['name' => 'San Lorenzo', 'code' => '1709'],
            ],
            '18' => [
                ['name' => 'Yoro', 'code' => '1801'],
                ['name' => 'Arenal', 'code' => '1802'],
                ['name' => 'El Negrito', 'code' => '1803'],
                ['name' => 'El Progreso', 'code' => '1804'],
                ['name' => 'Jocón', 'code' => '1805'],
                ['name' => 'Morazán', 'code' => '1806'],
                ['name' => 'Olanchito', 'code' => '1807'],
                ['name' => 'Santa Rita', 'code' => '1808'],
                ['name' => 'Sulaco', 'code' => '1809'],
                ['name' => 'Victoria', 'code' => '1810'],
                ['name' => 'Yorito', 'code' => '1811'],
            ],
        ];

        foreach ($data as $deptCode => $municipalities) {
            $department = Department::where('code', $deptCode)->first();
            if (! $department) {
                continue;
            }

            foreach ($municipalities as $mun) {
                Municipality::updateOrCreate(
                    [
                        'department_id' => $department->id,
                        'name' => $mun['name'],
                    ],
                    [
                        'code' => $mun['code'],
                    ]
                );
            }
        }
    }
}
