<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Clear all stale Yjs binary state columns so that editors start fresh
     * from their HTML content. This fixes a bug where the HTTP manual save
     * wrote client-side Yjs blobs that diverged from the Hocuspocus server's
     * authoritative state, causing content to revert on editor reopen.
     */
    public function up(): void
    {
        DB::table('specimen_reports')->update([
            'yjs_macroscopy_state' => null,
            'yjs_microscopy_state' => null,
            'yjs_diagnosis_state' => null,
            'yjs_report_date_state' => null,
            'yjs_clinical_details_state' => null,
            'yjs_comments_notes_state' => null,
            'yjs_protocols_state' => null,
            'yjs_legend_state' => null,
            'yjs_open_text_state' => null,
            'yjs_addendum_state' => null,
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * Cannot restore Yjs blobs — they will be regenerated by Hocuspocus
     * on the next edit session.
     */
    public function down(): void
    {
        // Yjs blobs are regenerated by the collaboration server on next edit;
        // no rollback is possible or necessary.
    }
};
