<?php

namespace App\Models;

use App\Casts\SectionsOrderCast;
use App\Traits\Auditable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class SpecimenReport extends Model
{
    use Auditable;
    use HasFactory;

    protected $table = 'specimen_reports';

    /**
     * The attributes that are mass assignable.
     *
     * The *_html columns store the rich text document contents generated by TipTap editors.
     * The yjs_*_state columns store the binary Yjs state vector updates for real-time collaboration.
     */
    protected $fillable = [
        'report_date',
        'generated_at',
        'macroscopy_html',
        'macroscopy_finalization_datetime',
        'microscopy_html',
        'microscopy_finalization_datetime',
        'diagnosis_html',
        'clinical_details_html',
        'comments_notes_html',
        'protocols_html',
        'legend_html',
        'report_finalization_datetime',
        'sections_order',
        'report_file',
    ];

    protected $casts = [
        'report_date' => 'date',
        'generated_at' => 'datetime',
        'macroscopy_finalization_datetime' => 'datetime',
        'microscopy_finalization_datetime' => 'datetime',
        'report_finalization_datetime' => 'datetime',
        'sections_order' => SectionsOrderCast::class,
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * We hide the binary Yjs document state vectors because they are only utilized internally
     * by the collaboration server and during initial document setup.
     */
    protected $hidden = [
        'yjs_macroscopy_state',
        'yjs_microscopy_state',
        'yjs_diagnosis_state',
        'yjs_report_date_state',
        'yjs_clinical_details_state',
        'yjs_comments_notes_state',
        'yjs_protocols_state',
        'yjs_legend_state',
    ];

    /**
     * Get the specimens associated with this report.
     */
    public function specimens(): HasMany
    {
        return $this->hasMany(Specimen::class, 'report_id');
    }
}
